version: "3"
services:
#  frontend:
#    build:
#      dockerfile: Dockerfile
#      context: ./frontend
#    volumes:
#      - /app/node_modules
#      - ./frontend:/app
#
#  nginx:
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - "3000:80"



  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "80:80"
    depends_on:
      - mysql


  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classee
      MYSQL_HOST : localhost
      MYSQL_PORT : 3306

  redis:
    image: redis
    ports:
      - "6379:6379"
